[package]
name = "nogine2-window"
version = "0.1.0"
edition = "2021"

[dependencies]
nogine2-core = { path = "../nogine2-core" }
nogine2-graphics = { path = "../nogine2-graphics" }
glfw-sys = "5.0.0"
bitflags = "2.6.0"
